import { ComparisonMetric, MetricTrend } from "../../analytics.types";

export interface KPIDefinition {
  key: string;
  name: string;
  description: string;
  formula: string;
  dataSource: string;
  aggregation: "SUM" | "AVG" | "RATIO" | "COUNT";
  timeGranularity: "HOURLY" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
}

export class KPIEngine {
  private static kpiRegistry: Map<string, KPIDefinition> = new Map([
    ["GMV", { key: "GMV", name: "Gross Merchandise Value", description: "Total value of merchandise & ticket orders before discounts", formula: "sum(ticket_price * ticket_count)", dataSource: "bookings", aggregation: "SUM", timeGranularity: "DAILY" }],
    ["NET_REVENUE", { key: "NET_REVENUE", name: "Net Revenue", description: "Gross revenue minus discounts and refunds plus fees & taxes", formula: "gross_revenue - discounts - refunds + fees + tax", dataSource: "daily_revenue_stats", aggregation: "SUM", timeGranularity: "DAILY" }],
    ["ARPU", { key: "ARPU", name: "Average Revenue Per User", description: "Total net revenue divided by total active users", formula: "net_revenue / active_users", dataSource: "daily_user_stats & daily_revenue_stats", aggregation: "AVG", timeGranularity: "MONTHLY" }],
    ["AVERAGE_ORDER_VALUE", { key: "AVERAGE_ORDER_VALUE", name: "Average Order Value", description: "Net revenue divided by successful booking count", formula: "net_revenue / successful_bookings", dataSource: "daily_booking_stats", aggregation: "AVG", timeGranularity: "DAILY" }],
    ["BOOKING_CONVERSION", { key: "BOOKING_CONVERSION", name: "Booking Conversion Rate", description: "Percentage of booking attempts that result in confirmed bookings", formula: "(confirmed_bookings / booking_attempts) * 100", dataSource: "daily_booking_stats", aggregation: "RATIO", timeGranularity: "HOURLY" }],
    ["OCCUPANCY_RATE", { key: "OCCUPANCY_RATE", name: "Occupancy Rate", description: "Percentage of sellable seats sold across showtimes", formula: "(sold_seats / total_sellable_seats) * 100", dataSource: "daily_show_stats", aggregation: "RATIO", timeGranularity: "HOURLY" }],
    ["PAYMENT_SUCCESS_RATE", { key: "PAYMENT_SUCCESS_RATE", name: "Payment Success Rate", description: "Percentage of successful payments over payment attempts", formula: "(successful_payments / payment_attempts) * 100", dataSource: "daily_payment_stats", aggregation: "RATIO", timeGranularity: "HOURLY" }],
    ["REFUND_RATE", { key: "REFUND_RATE", name: "Refund Rate", description: "Percentage of confirmed bookings that were refunded", formula: "(refunded_bookings / confirmed_bookings) * 100", dataSource: "daily_booking_stats", aggregation: "RATIO", timeGranularity: "DAILY" }],
    ["CUSTOMER_RETENTION", { key: "CUSTOMER_RETENTION", name: "Customer Retention Rate", description: "Percentage of active users retained after D1, D7, or D30", formula: "(active_cohort / initial_cohort) * 100", dataSource: "daily_user_stats", aggregation: "RATIO", timeGranularity: "MONTHLY" }],
    ["COUPON_ROI", { key: "COUPON_ROI", name: "Coupon ROI", description: "Revenue generated by coupon redemptions relative to discount cost", formula: "((revenue_generated - discount_cost) / discount_cost) * 100", dataSource: "daily_coupon_stats", aggregation: "RATIO", timeGranularity: "DAILY" }],
    ["CAMPAIGN_ROI", { key: "CAMPAIGN_ROI", name: "Campaign ROI", description: "Return on marketing campaign investment", formula: "((campaign_revenue - campaign_cost) / campaign_cost) * 100", dataSource: "daily_campaign_stats", aggregation: "RATIO", timeGranularity: "DAILY" }],
  ]);

  public static getKPIDefinitions(): KPIDefinition[] {
    return Array.from(this.kpiRegistry.values());
  }

  public static getKPIDefinition(key: string): KPIDefinition | undefined {
    return this.kpiRegistry.get(key.toUpperCase());
  }

  public static calculateOccupancyRate(soldSeats: number, totalSeats: number): number {
    if (totalSeats <= 0) return 0;
    return Number(((soldSeats / totalSeats) * 100).toFixed(2));
  }

  public static calculateBookingConversion(confirmedBookings: number, attempts: number): number {
    if (attempts <= 0) return 0;
    return Number(((confirmedBookings / attempts) * 100).toFixed(2));
  }

  public static calculatePaymentSuccessRate(successful: number, totalAttempts: number): number {
    if (totalAttempts <= 0) return 0;
    return Number(((successful / totalAttempts) * 100).toFixed(2));
  }

  public static calculateAverageOrderValue(netRevenueMinor: number, successfulBookings: number): number {
    if (successfulBookings <= 0) return 0;
    return Math.round(netRevenueMinor / successfulBookings);
  }

  public static calculateRefundRate(refundedCount: number, confirmedCount: number): number {
    if (confirmedCount <= 0) return 0;
    return Number(((refundedCount / confirmedCount) * 100).toFixed(2));
  }

  public static calculateARPU(netRevenue: number, activeUsers: number): number {
    if (activeUsers <= 0) return 0;
    return Number((netRevenue / activeUsers).toFixed(2));
  }

  public static calculateCouponROI(revenueGenerated: number, discountCost: number): number {
    if (discountCost <= 0) return 0;
    return Number((((revenueGenerated - discountCost) / discountCost) * 100).toFixed(2));
  }

  public static calculateCampaignROI(campaignRevenue: number, campaignCost: number): number {
    if (campaignCost <= 0) return 0;
    return Number((((campaignRevenue - campaignCost) / campaignCost) * 100).toFixed(2));
  }

  public static calculateScreenUtilization(actualShows: number, maxShowSlots: number): number {
    if (maxShowSlots <= 0) return 0;
    return Number(((actualShows / maxShowSlots) * 100).toFixed(2));
  }

  public static calculateRetention(activeCohort: number, initialCohort: number): number {
    if (initialCohort <= 0) return 0;
    return Number(((activeCohort / initialCohort) * 100).toFixed(2));
  }

  public static calculateComparison(current: number, previous: number): ComparisonMetric {
    const change = current - previous;
    let percentage = 0;
    if (previous !== 0) {
      percentage = Number(((change / previous) * 100).toFixed(2));
    } else if (current > 0) {
      percentage = 100;
    }

    let trend: MetricTrend = "FLAT";
    if (change > 0) trend = "UP";
    else if (change < 0) trend = "DOWN";

    return {
      current,
      previous,
      change,
      percentage,
      trend,
    };
  }
}
